package meter

// Code generated by github.com/xerion3800/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/xerion3800/evcc/api"
)

func decorateBoschBpts5Hybrid(base api.Meter, battery func() (float64, error)) api.Meter {
	switch {
	case battery == nil:
		return base

	case battery != nil:
		return &struct {
			api.Meter
			api.Battery
		}{
			Meter: base,
			Battery: &decorateBoschBpts5HybridBatteryImpl{
				battery: battery,
			},
		}
	}

	return nil
}

type decorateBoschBpts5HybridBatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decorateBoschBpts5HybridBatteryImpl) Soc() (float64, error) {
	return impl.battery()
}
