name: Bug report
description: Create a report to help us improve

body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting issues only! If you want to start a discussion or ask a question, please use the [discussion forum][df].

        **NOTE** Due to amount of issues raised we will close incomplete issues (unclear description what the issue actually is, missing log file, unsupported platform) without further comments.

        [df]: https://github.com/evcc-io/evcc/discussions
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: >-
        A clear and concise description of what the bug is.

  - type: textarea
    validations:
      required: true
    attributes:
      value: |
        1.
        2.
        3.
        ...
      label: Steps to reproduce
      description: >-
        Steps to reproduce the behavior.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Configuration details
      render: yaml
      description: >
        Show evcc configuration file <code>evcc.yaml</code>

  - type: textarea
    validations:
      required: true
    attributes:
      label: Log details
      render: text
      description: >
        Show evcc log output by running with <code>evcc --log debug</code>. The evcc service **MUST** be stopped before running this command.

  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of operating system are you running?
      description: >
        **NOTE** if you're using HomeAssistant or Docker we ask you to reproduce the problem on plain Linux or Windows first.
      options:
        - Linux
        - Windows
        - Docker container
        - HomeAssistant Add-on

  - type: input
    attributes:
      label: Version
      description: >
        Show output of <code>evcc -v</code>
